import React from 'react';
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconNames;
  size: string | number;
  theme: 'light' | 'dark';
}

export type ThemeOptions = {
  light: string;
  dark?: string;
};

export interface IIconLibrary {
  title: IconNames;
  category: string;
  icon: ThemeOptions;
  url: string;
  other_names: string[];
}

export interface SVGElementData {
  type: string;
  props: Record<string, any>;
  children: SVGElementData[];
}

export type IconNames =
  | 'PayPal'
  | 'Google Drive'
  | 'Milanote'
  | 'Together AI'
  | 'Suno'
  | 'Groq'
  | 'Cohere'
  | 'Ollama'
  | 'Cisco'
  | 'Animate'
  | 'Apollo.io'
  | 'Blender'
  | 'Lua'
  | 'Mercado Pago'
  | 'Basewell'
  | 'ahooks'
  | 'Discord'
  | 'Aliexpress'
  | 'Github'
  | 'Preact'
  | 'React'
  | 'Svelte'
  | 'Vue'
  | 'Vuetify'
  | 'Nuxt'
  | 'Visual Studio Code'
  | 'Ton'
  | 'Locofy'
  | 'Runway'
  | 'Yarn'
  | 'JWT'
  | 'Strapi'
  | 'Figma'
  | 'Spotify'
  | 'WorkOS'
  | 'Whop'
  | 'Postman'
  | 'Discord.js'
  | 'OpenSea'
  | 'Algolia'
  | 'Bootstrap'
  | 'Facebook'
  | 'Twitter'
  | 'Esbuild'
  | 'Deno'
  | 'Gatsby'
  | 'NPM'
  | 'Homebrew'
  | 'Sublime Text'
  | 'Turborepo'
  | 'Tailwind CSS'
  | 'Styled Components'
  | 'Angular'
  | 'Blitz'
  | 'Lit'
  | 'Atom'
  | 'YouTube'
  | 'Astro'
  | 'Google'
  | 'Framer'
  | 'Netflix'
  | 'Firefox'
  | 'LinkedIn'
  | 'Telegram'
  | 'WhatsApp'
  | 'Headless UI'
  | 'Kotlin'
  | 'Storybook'
  | 'Netlify'
  | 'Solidjs'
  | 'MongoDB'
  | 'Moon'
  | 'Payload CMS'
  | 'Fly'
  | 'LearnThis'
  | 'Visual Studio'
  | 'Chakra UI'
  | 'Express.js'
  | 'Fastify'
  | 'JavaScript'
  | 'jQuery'
  | 'Rapid API'
  | 'TypeScript'
  | 'Bun'
  | 'BuildShip'
  | 'Twilio'
  | 'Arc'
  | 'Arc'
  | 'Qwik'
  | 'Coinbase'
  | 'Authy'
  | 'NestJS'
  | 'GitHub Copilot'
  | 'Railway'
  | 'Docusaurus'
  | 'Twitch'
  | 'GoDaddy'
  | 'Udemy'
  | 'GraphQL'
  | 'GitLab'
  | 'Prisma'
  | 'Go'
  | 'Platzi'
  | 'Coursera'
  | 'Udacity'
  | 'Kubernetes'
  | 'Docker'
  | 'Amazon Web Services'
  | 'Microsoft Azure'
  | 'Heroku'
  | 'JetBrains'
  | 'JetBrains Rider'
  | 'PlanetScale'
  | 'Playwright'
  | 'Atlassian'
  | 'Discourse'
  | 'Ember'
  | 'Expo'
  | 'Flutter'
  | 'Auth0'
  | 'Fresh'
  | 'Git'
  | 'Hostgator'
  | 'IntelliJ IDEA'
  | 'Jasmine'
  | 'Java'
  | 'Jest'
  | 'JetBrains'
  | 'KrakenJS'
  | 'Laravel'
  | 'MariaDB'
  | 'Material UI'
  | 'MySQL'
  | 'Parcel'
  | 'PM2'
  | 'PostgreSQL'
  | 'React Query'
  | 'Devto'
  | 'Redis'
  | 'RedwoodJS'
  | 'Ruby'
  | 'Scala'
  | 'Sequelize'
  | 'Spinnaker'
  | 'SQLite'
  | 'Swagger'
  | 'Swift'
  | 'TypeORM'
  | 'Unity'
  | 'Vim'
  | 'Pocketbase'
  | 'OpenBootcamp'
  | 'Digital Ocean'
  | 'Disney+'
  | 'React Router'
  | 'AMP'
  | 'Developer Student Club'
  | 'Brave Browser'
  | 'Eclipse IDE'
  | 'Three.js'
  | 'HTML5'
  | 'CSS (New)'
  | 'CSS'
  | 'midudev'
  | 'Apple'
  | 'Windows'
  | 'Python'
  | 'Solidity'
  | 'Turbopack'
  | 'Builder'
  | 'Babel'
  | 'Surrealdb'
  | 'Jetbrains Space'
  | 'Stimulus'
  | 'WindiCSS'
  | 'Mastodon'
  | 'Upstash'
  | 'Storyblok'
  | 'Cloudflare Workers'
  | 'Cloudflare'
  | 'Bing'
  | 'Cloudinary'
  | 'Dart'
  | 'hCaptcha'
  | 'Appwrite'
  | 'Loom'
  | 'Hulu'
  | 'Stackblitz'
  | 'Binance'
  | 'Messenger'
  | 'NHost'
  | 'Medusa'
  | 'WordPress'
  | 'Microsoft'
  | 'Elementor'
  | 'Kick'
  | 'Prime video'
  | 'Chrome'
  | 'RxJS'
  | 'Electron'
  | 'Redux'
  | 'Trust Wallet'
  | 'Php'
  | 'Hugo'
  | 'Sass'
  | 'Arc'
  | 'Pinia'
  | 'Neon'
  | 'Infojobs'
  | 'Linear'
  | 'Tor'
  | 'Codesandbox'
  | 'Skype'
  | 'Tauri'
  | 'WebKit'
  | 'DuckDuckGo'
  | 'Obsidian'
  | 'Zod'
  | 'Dreamweaver'
  | 'OpenAI'
  | 'Threads'
  | 'Instagram'
  | 'VueUse'
  | 'Microsoft SQL Server '
  | 'Hono'
  | 'Million'
  | 'PandaCSS'
  | 'Pulumi'
  | 'FastAPI'
  | 'Codium'
  | 'Crossplane'
  | 'Volta'
  | 'Typesense'
  | 'Bitcoin'
  | 'Ethereum'
  | 'Solana'
  | 'Dogecoin'
  | 'XRP'
  | 'BNB'
  | 'Link'
  | 'Polygon'
  | 'Algorand'
  | 'Tether'
  | 'X (formerly Twitter)'
  | 'Adobe'
  | 'After Effects'
  | 'Canva'
  | 'Illustrator'
  | 'InDesign'
  | 'Lightroom'
  | 'Photoshop'
  | 'Premiere'
  | 'VK'
  | 'Hoppscotch'
  | 'Opera'
  | 'Salesforce'
  | 'Unreal Engine'
  | 'Godot Engine'
  | 'Datadog'
  | 'Tron'
  | 'Randevum'
  | 'Chromium'
  | 'Edge'
  | 'Safari'
  | 'Vivaldi'
  | 'Beacon'
  | 'Affinity Designer'
  | 'Affinity Photo'
  | 'Affinity Publisher'
  | 'Roblox'
  | 'Stately.ai'
  | 'XState'
  | 'Hashnode'
  | 'Rowy'
  | 'Cal.com'
  | 'Calendly'
  | 'Mintlify'
  | 'Patreon'
  | 'Peerlist'
  | 'Product Hunt'
  | 'Remotion'
  | 'Warp'
  | 'SST'
  | 'Documenso'
  | 'Bash'
  | 'C'
  | 'C++'
  | 'Cobol'
  | 'Fortran'
  | 'Haskell'
  | 'matlab'
  | 'R'
  | 'Rust'
  | 'Zig'
  | 'Instatus'
  | 'Front'
  | 'Monero'
  | 'Axiom'
  | 'Django'
  | 'Zeabur'
  | 'MetaMask'
  | 'shadcn/ui'
  | 'putio'
  | 'Pinterest'
  | 'Reflex'
  | 'Stripe'
  | 'Linux'
  | 'XD'
  | 'Axure'
  | 'Penpot'
  | 'Sketch'
  | 'Gimp'
  | 'Ubuntu'
  | 'Cypress'
  | 'Reddit'
  | 'JetBrains WebStorm'
  | 'JetBrains PyCharm'
  | 'JetBrains Fleet'
  | 'JetBrains RubyMine'
  | 'JetBrains PhpStorm'
  | 'Monkeytype'
  | 'PyCharm'
  | 'Shopify'
  | 'WebFlow'
  | 'Sanity'
  | 'sky'
  | 'Airbnb'
  | 'Uber'
  | 'Gmail'
  | 'Outlook'
  | 'Slack'
  | 'Snapchat'
  | 'Ebay'
  | 'IBM'
  | 'TrustPilot'
  | 'Raycast'
  | 'Hack The Box'
  | 'Procure'
  | 'Julia'
  | 'SWC'
  | 'PlayStation'
  | 'Xbox'
  | 'Cody'
  | 'Sourcegraph'
  | 'Perplexity AI'
  | 'Spring'
  | 'Directus'
  | 'Pnpm'
  | 'Emacs'
  | 'Svgl'
  | 'Google Idx'
  | 'Remix'
  | 'Steam'
  | 'Tabby'
  | '1Password'
  | 'Flask'
  | 'Alacritty'
  | 'Qt'
  | 'Bitwarden'
  | 'Voicemod'
  | 'Neovim'
  | 'Pitch'
  | 'Biomejs'
  | 'Gradio'
  | 'Meta'
  | 'Stability AI'
  | 'Google PaLM'
  | 'Android'
  | 'Sentry'
  | 'Grafana'
  | 'Notion'
  | 'Litecoin'
  | 'ElysiaJS'
  | 'TensorFlow'
  | 'Midday'
  | 'C#'
  | 'Replicate'
  | 'Markdown'
  | 'Radix UI'
  | 'Web.dev'
  | 'SWR'
  | 'Refine'
  | 'Youtube Music'
  | 'TIDAL'
  | 'OBS'
  | 'Stack Overflow'
  | 'TikTok'
  | 'Ngrok'
  | 'Lemon Squeezy'
  | 'Asana'
  | 'UpLeveled'
  | 'Zoom'
  | 'Tina'
  | 'Next.js'
  | 'Mistral AI'
  | 'Hugging Face'
  | 'Node.js'
  | 'Raindrop.io'
  | 'Microsoft Todo'
  | 'Supabase'
  | 'Gleam'
  | 'Flowbite'
  | 'Hume AI'
  | 'Resend'
  | 'Layers'
  | 'Exome'
  | 'Poper'
  | 'Dub'
  | 'Turso'
  | 'RelaGit'
  | 'T3 Stack'
  | 'Apple Music'
  | 'YGeeker'
  | 'Web components'
  | 'PostCSS'
  | 'SVG'
  | 'Todoist'
  | 'Apidog'
  | 'Chart.js'
  | 'JSON Schema'
  | 'v0'
  | 'Bento'
  | 'Firebase'
  | 'Prettier'
  | 'Leap Wallet'
  | 'Nx'
  | 'Google Colaboratory'
  | 'Raspberry PI'
  | 'Vite'
  | 'Vitest'
  | 'Oxc'
  | 'Rolldown'
  | 'ManzDev'
  | 'Afordin'
  | 'MediaWiki'
  | 'Carrd'
  | 'Claude AI'
  | 'UnoCSS'
  | 'tRPC'
  | 'Bluesky'
  | 'Drizzle ORM'
  | 'daily.dev'
  | 'Polars'
  | 'Zed'
  | 'Polar'
  | 'bolt'
  | 'JSON'
  | 'nuqs'
  | 'SoundCloud'
  | 'Clerk'
  | 'Mermaid'
  | 'Home Assistant'
  | 'UXAnaRangel'
  | 'UXCorpRangel'
  | 'PostHog'
  | 'Lottielab'
  | 'TanStack'
  | 'TypeGPU'
  | 'dotenv'
  | 'dotenvx'
  | 'Motion'
  | 'Keycloak'
  | 'DeepSeek'
  | 'Shiki'
  | 'Dropbox'
  | 'Open WebUI'
  | 'Base UI'
  | 'Vercel'
  | 'Socket.io'
  | 'Ant Design'
  | 'VSCodium'
  | 'Zen Browser'
  | 'Gemini'
  | 'xAI (Grok)'
  | 'Qwen'
  | 'Inflection AI'
  | 'D3.js';
