/**
 * Copyright (c). All rights reserved.
 * The SVG content and associated code are unmodified and belong to their respective owners.
 * 
 * This file is automatically generated.
 */

import * as React from 'react';
import { IconProps } from '../types';

/**
 * AngularJsIcon component.
 * - A React component that renders the provided SVG content.
 * - Accepts a `size` prop to control the width and height.
 */
export const AngularJsIcon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ size = 200, ...props }, forwardedRef) => (
    <svg 
    width={size} 
    height={size} 
    {...props} 
    ref={forwardedRef}>
    <path fill='#dd0031' d='M16 2 2.966 6.648l1.988 17.234L16 30l11.046-6.118 1.988-17.234z' /><path fill='#c3002f' d='M16 2v3.108-.014V30l11.046-6.118 1.988-17.234z' /><path d='m16 5.094-8.148 18.27h3.038l1.638-4.088h6.916l1.638 4.088h3.038zm2.38 11.662h-4.76L16 11.03Z' fill='#fff' /></svg>
  )
);

AngularJsIcon.displayName = 'AngularJsIcon';