/**
 * Copyright (c). All rights reserved.
 * The SVG content and associated code are unmodified and belong to their respective owners.
 * 
 * This file is automatically generated.
 */

import * as React from 'react';
import { IconProps } from '../types';

/**
 * RadixUIIcon component.
 * - A React component that renders the provided SVG content.
 * - Accepts a `size` prop to control the width and height.
 */
export const RadixUIIcon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ size = 200, ...props }, forwardedRef) => (
    <svg 
    width={size} 
    height={size} 
    {...props} 
    ref={forwardedRef}>
    <path d='M1.152 2.4a.768.768 0 1 1 0-1.536zm0-2.4H.384v.768h.768zm.48.768a.384.384 0 1 0 0-.768.384.384 0 0 0 0 .768' fill='currentcolor' /></svg>
  )
);

RadixUIIcon.displayName = 'RadixUIIcon';