/**
 * Copyright (c). All rights reserved.
 * The SVG content and associated code are unmodified and belong to their respective owners.
 * 
 * This file is automatically generated.
 */

import * as React from 'react';
import { IconProps } from '../types';

/**
 * ShadcnUIIcon component.
 * - A React component that renders the provided SVG content.
 * - Accepts a `size` prop to control the width and height.
 */
export const ShadcnUIIcon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ size = 200, ...props }, forwardedRef) => (
    <svg 
    width={size} 
    height={size} 
    {...props} 
    ref={forwardedRef}>
    <path fill='none' d='M0 0h240v240H0z' /><path d='m195 120-75 75m60-157.5L37.5 180' fill='none' stroke='#000' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32px' /></svg>
  )
);

ShadcnUIIcon.displayName = 'ShadcnUIIcon';